### ISSUE TITLE
NameError: name 'OPTION' is not defined

### ISSUE THREAD

**Issue by Trhova** [patrickbryant1/EvoBind#9]
Hello! I got the following syntax; 

NameError                                 Traceback (most recent call last)
[<ipython-input-12-384040ceaa3e>](https://localhost:8080/#) in <module>
     19 from af_mod_pred import run_preds
     20 TARGET_FASTA=OUTDIR+PDBID+'_'+TARGET_CHAIN+'.fasta'
---> 21 if OPTION=='1':
     22   TARGET_MSA=OUTDIR+'/str_aln/'+PDBID+'_str.a3m'
     23 else:

NameError: name 'OPTION' is not defined 

When attempting to use the google colab sheet under the 

#@markdown #Evaluate the designed sequences using our modified version of [AlphaFold](https://www.nature.com/articles/s41586-021-03819-2) adapted to binder evaluation.
#@markdown The designed sequences are predicted in complex with the target. 
#@markdown The predictions are used below to assess the designs by calculating a custom bind-score.

I tried with the example protein as well as my own protein of interest and got the same error. 

Any suggestions? 

I think the work you have done is super exciting and I hope I can make this work (I intend to validate binders with wet-lab experiments asap). 

Best, 

Troels

**Comment by patrickbryant1** [comment]
Hi,
Great to hear that you like this work. A new version of EvoBind will be out soon (under review) and I think this is the version you have found. I know some people are using this, but we have not officially released this yet. Now you are reporting an issue in the old version.

The error you get is due to not running the above cells I think. As you can see in "Get MSA for the target" the variable OPTION is set.

If you aim to validate designs, perhaps we can help you with the designs if this would be of interest? Please email me at patrick.bryant@scilifelab.se and tell me about your project if this is the case.

Best,

Patrick
